Update sshc

diff --git a/sshc b/sshc
--- a/sshc
+++ b/sshc
@@ -15,7 +15,6 @@ fi
 
 # data base location , Don not change this form
 database_en="/etc/sshc/sshc.database.en"
-#database_de="/etc/sshc/sshc.database.de"
 
 
 # echo header on terminal
@@ -23,10 +22,10 @@ reset
 echo '[+] ------------------------------------------------------------------- [+]'
 echo -e "[+] Programming and idea by : \e[1mE2MA3N [Iman Homayouni]\e[0m"
 echo '[+] License : GPL v3.0'
-echo -e '[+] sshc v2.0 \n'
+echo -e '[+] sshc v3.0 \n'
 
 
-# check database_de
+# check encrypted database
 if [ ! -f $database_en ] ; then
 	echo -e "[-] Error:"
 	echo -e "[-] $database_en not found"
@@ -34,18 +33,21 @@ if [ ! -f $database_en ] ; then
 	exit 1
 fi
 
-echo -en "[+] Enter password: " ; read pass
+
+# decrypt database
+echo -en "[+] Enter password: " ; read -s pass
 database_de=`openssl aes-256-cbc -pass pass:$pass -d -a -in $database_en 2> /dev/null`
 if [ "$?" != "0" ] ; then
-	echo "[-] Error: Database can not encrypted."
+	echo -e "\n[-] Error: Database can not encrypted."
 	echo '[+] ------------------------------------------------------------------- [+]'
 	exit 1
 else
 	echo
 fi
 
-# echo servers informations on terminal
-echo -e " 0) Edite Database"
+
+# print servers informations on terminal
+echo -e "\n 0) Edite Database"
 var0=`echo "$database_de" | wc -l`
 var0=`expr $var0 - 11`
 for (( i=1 ; i <= $var0 ; i++ )) ; do
@@ -56,13 +58,14 @@ done
 # edite database
 function edit_db {
 	echo "$database_de" | joe /etc/sshc/sshc.database.de
-	echo -en "[+] encrypt new database, Please type your password: " ; read pass
+	echo -en "[+] encrypt new database, Please type your password: " ; read -s pass
 	openssl aes-256-cbc -pass pass:$pass -a -salt -in /etc/sshc/sshc.database.de -out $database_en
 	rm -f /etc/sshc/sshc.database.de
-	echo -e "[+] Done, New database saved and encrypted"
+	echo -e "\n[+] Done, New database saved and encrypted"
 	echo '[+] ------------------------------------------------------------------- [+]'
 	exit 0
 }
+
 
 # select server for continue
 while :; do
@@ -84,8 +87,6 @@ else
 	exit 1
 fi
 done
-
-
 
 
 # connect to server
@@ -110,14 +111,24 @@ function function_2 {
 	username=`echo "$database_de" | tail -n $var1 | head -n 1 | cut -d " " -f 1`
 	ssh_port=`echo "$database_de" | tail -n $var1 | head -n 1 | cut -d " " -f 3`
 	ip_address=`echo "$database_de" | tail -n $var1 | head -n 1 | cut -d " " -f 2`
-	var3=`curl ipecho.net/plain 2> /dev/null`
-	echo -en "[+] $var3 your IP Address ? [y/n]: " ; read var4
+	for (( i=1 ; i < 4 ; i++ )) ; do
+		public_ip=`curl ipecho.net/plain 2> /dev/null`
+		if [ ! -z "$public_ip" ]; then
+			break
+		fi
+	done
+	echo -en "[+] $public_ip your public IP Address ? [y/n]: " ; read var4
 	if [ "$var4" = "y" ] ; then
-	sshpass -p "$password" ssh -o StrictHostKeyChecking=no -l $username $ip_address -p $ssh_port "iptables -I INPUT -s $var3 -j ACCEPT"
+		sshpass -p "$password" ssh -o StrictHostKeyChecking=no -l $username $ip_address -p $ssh_port "iptables -I INPUT -s $public_ip -j ACCEPT" &> /dev/null
+		if [ "$?" != "0" ] ; then
+			echo "[-] Error: Can not connect to server."
+			echo '[+] ------------------------------------------------------------------- [+]'
+			exit 1
+		fi
 	else
-	echo "[+] Bye Bye"
-	echo '[+] ------------------------------------------------------------------- [+]'
-	exit 1
+		echo "[+] Bye Bye"
+		echo '[+] ------------------------------------------------------------------- [+]'
+		exit 1
 	fi
 }
 
@@ -135,7 +146,7 @@ if [ "`echo "$database_de" | tail -n $var1 | head -n 1 | cut -d " " -f 1`" != "r
 	echo -e "\e[0m 1) Connect to server"
 else
 	echo -e "\e[0m 1) Connect to server"
-	echo -e " 2) Open your IP address in server"
+	echo -e " 2) Open your public IP address in server (Firewall)"
 	echo -e " 3) Both"	
 fi
 
